//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFHaberinDBService
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public News()
        {
            this.Comments = new HashSet<Comment>();
            this.Writers = new HashSet<Writer>();
        }
    
        public int NewsID { get; set; }
        public string NewsTitle { get; set; }
        public string NewsDescription { get; set; }
        public string NewsContent { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<int> ViewPoint { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> isBigNew { get; set; }
        public Nullable<int> DirectorID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Director Director { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<Writer> Writers { get; set; }
    }
}
