//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCHaberinDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Director
    {
        public Director()
        {
            this.Directors1 = new HashSet<Director>();
            this.News = new HashSet<News>();
        }
    
        public int DirectorID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string Address { get; set; }
        public Nullable<int> ReportsTo { get; set; }
        public string Imagepath { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> RoleID { get; set; }
    
        public virtual ICollection<Director> Directors1 { get; set; }
        public virtual Director Director1 { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<News> News { get; set; }
    }
}
