//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCHaberinDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Writer
    {
        public Writer()
        {
            this.News = new HashSet<News>();
        }
    
        public int WriterID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ImagePath { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<News> News { get; set; }
    }
}
